import { defineConfig } from 'vite-plus';

export default defineConfig({
  staged: { '*': 'vp check --fix' },
  lint: {
    options: { typeAware: true, typeCheck: true },
    ignorePatterns: ['**/dist/**', '**/node_modules/**', '**/generated/**', '.vite-hooks/**'],
    categories: { correctness: 'warn' },
    rules: {
      'eslint/eqeqeq': 'error',
      'eslint/max-classes-per-file': ['error', 1],
      'eslint/max-lines': ['error', 400],
      'eslint/no-empty-function': 'warn',
      'eslint/no-restricted-imports': 'warn',
      'eslint/no-shadow': 'warn',
      'eslint/no-unused-expressions': 'off',
      'eslint/no-unused-private-class-members': 'warn',
      'eslint/no-unused-vars': 'warn',
      'eslint/no-useless-concat': 'error',
      'eslint/no-var': 'error',
      'eslint/prefer-const': 'warn',
      'eslint/prefer-destructuring': 'warn',
      'eslint/prefer-spread': 'error',
      'eslint/prefer-template': 'warn',
      // 'eslint/sort-imports': 'error',
      'import/no-absolute-path': 'error',
      'import/unambiguous': 'error',
      'jsdoc/require-param-type': 'warn',
      'jsdoc/require-param': 'warn',
      'promise/prefer-await-to-callbacks': 'warn',
      'promise/prefer-await-to-then': 'warn',
      'typescript/consistent-indexed-object-style': ['error', 'record'],
      'typescript/consistent-type-exports': 'error',
      'typescript/no-explicit-any': 'warn',
      'typescript/no-extraneous-class': 'off',
      'typescript/no-floating-promises': 'warn',
      'typescript/no-import-type-side-effects': 'error',
      'typescript/no-inferrable-types': 'error',
      'typescript/no-misused-promises': 'warn',
      'typescript/no-unnecessary-condition': 'off',
      'typescript/no-unnecessary-parameter-property-assignment': 'error',
      'typescript/no-unnecessary-qualifier': 'error',
      'typescript/no-unnecessary-template-expression': 'error',
      'typescript/no-unsafe-argument': 'off',
      'typescript/no-unsafe-assignment': 'off',
      'typescript/no-unsafe-call': 'off',
      'typescript/no-unsafe-member-access': 'off',
      'typescript/no-unsafe-return': 'error',
      'typescript/prefer-as-const': 'warn',
      'typescript/prefer-for-of': 'warn',
      'typescript/prefer-function-type': 'error',
      'typescript/prefer-optional-chain': 'off',
      // 'typescript/prefer-readonly-parameter-types': 'warn',
      // 'typescript/prefer-readonly': 'warn',
      'typescript/promise-function-async': 'off',
      // 'typescript/require-await': 'error',
      'typescript/restrict-template-expressions': 'error',
      'typescript/return-await': 'error',
      'typescript/unbound-method': 'off',
    },
    settings: {
      jsdoc: {
        ignorePrivate: false,
        ignoreInternal: false,
        ignoreReplacesDocs: true,
        overrideReplacesDocs: true,
        augmentsExtendsReplacesDocs: false,
        implementsReplacesDocs: false,
        exemptDestructuredRootsFromChecks: false,
        tagNamePreference: {},
      },
      vitest: { typecheck: false },
    },
    env: { builtin: true },
  },
  fmt: {
    ignorePatterns: ['**/dist/**', '**/node_modules/**', '**/generated/**'],
    printWidth: 100,
    arrowParens: 'avoid',
    bracketSameLine: true,
    bracketSpacing: true,
    quoteProps: 'as-needed',
    semi: true,
    singleQuote: true,
    singleAttributePerLine: true,
    proseWrap: 'never',
    // objectWrap: 'preserve',
    trailingComma: 'all',
    useTabs: false,
    tabWidth: 2,
    embeddedLanguageFormatting: 'auto',
    sortImports: {
      sortSideEffects: true,
      groups: [
        ['side_effect-builtin', 'side_effect-external'],
        ['side_effect-internal', 'side_effect-subpath'],
        ['type-builtin', 'type-external', 'value-builtin', 'value-external'],
        ['type-internal', 'type-subpath', 'value-internal', 'value-subpath'],
        [
          'type-parent',
          'type-sibling',
          'type-index',
          'value-parent',
          'value-sibling',
          'value-index',
        ],
        ['side_effect_style', 'style'],
        'unknown',
      ],
    },
    overrides: [
      // { files: ['*.ts'], options: { objectWrap: 'preserve' } },
      { files: ['*.css'], options: { singleQuote: false } },
      { files: ['*.json', '*.jsonc'], options: { trailingComma: 'none', sortPackageJson: false } },
    ],
  },
  run: { cache: true },
});
