@api_HostAddress = http://localhost:5066
@email = admin@admin.local
@password = password123
@accessToken = replace-me-after-signin

### Sign in
POST {{api_HostAddress}}/auth/signin
Content-Type: application/json
Accept: application/json

{
	"email": "{{email}}",
	"password": "{{password}}"
}

### Verify current token
GET {{api_HostAddress}}/auth/is-authenticated
Authorization: Bearer {{accessToken}}
Accept: application/json

### Verify without token
GET {{api_HostAddress}}/auth/is-authenticated
Accept: application/json
